services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: riai_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app/artifacts:/app/app/artifacts
      - ./app/registry:/app/app/registry
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: riai_frontend
    depends_on:
      - backend
    ports:
      - "5174:80"
    environment:
      - NGINX_PORT=80
